"""add is_cover to image

Revision ID: 0f3dc345217c
Revises: 67aa695fabc1
Create Date: 2023-05-02 11:29:08.850390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3dc345217c'
down_revision = '67aa695fabc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('is_cover', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'is_cover')
    # ### end Alembic commands ###
