"""create base tables

Revision ID: 67aa695fabc1
Revises: 
Create Date: 2023-04-25 07:27:01.224843

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import AutoString


# revision identifiers, used by Alembic.
revision = '67aa695fabc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', AutoString(), nullable=False),
    sa.Column('country_code', AutoString(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', AutoString(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', AutoString(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', AutoString(), nullable=True),
    sa.Column('longitude', AutoString(), nullable=True),
    sa.Column('address', AutoString(), nullable=False),
    sa.Column('lga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lga_id'], ['lga.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', AutoString(), nullable=False),
    sa.Column('description', AutoString(), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', AutoString(), nullable=False),
    sa.Column('public_id', AutoString(), nullable=False),
    sa.Column('description', AutoString(), nullable=True),
    sa.Column('home_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('home')
    op.drop_table('location')
    op.drop_table('lga')
    op.drop_table('state')
    op.drop_table('country')
    # ### end Alembic commands ###
