"""add image, home, location, state and lga tables

Revision ID: 860fb85702b1
Revises: 
Create Date: 2023-04-17 06:18:02.834693

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import AutoString


# revision identifiers, used by Alembic.
revision = '860fb85702b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', AutoString(), nullable=False),
    sa.Column('url', AutoString(), nullable=False),
    sa.Column('description', AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', AutoString(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', AutoString(), nullable=True),
    sa.Column('longitude', AutoString(), nullable=True),
    sa.Column('address', AutoString(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('lga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lga_id'], ['lga.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', AutoString(), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('cover_photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cover_photo_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home')
    op.drop_table('location')
    op.drop_table('lga')
    op.drop_table('state')
    op.drop_table('image')
    # ### end Alembic commands ###
